### PR TITLE
small parameter fix

### PR DESCRIPTION
**Pull request by EyalPazz**
fixing the hugging face parameter issue + temperature default value should be 1

### CODE REVIEW

**Comment by vprelovac** [comment]
Lets not change default values.

Just want to make sure - what model is using max_length and have you checkd that is compatible with the other supported models?

**Comment by EyalPazz** [comment]
don't you think that default values should be the same default values the provider gives? and as for the second question all of the models via the hugging face inference API are using max_length as the name of the parameter : https://huggingface.co/docs/api-inference/detailed_parameters

**Comment by vprelovac** [comment]
We'd like to keep the default value in line with the default values for other models where temp is zeo for maximum consistency/reproducibility of results (also important when benchmarking models).

**Comment by EyalPazz** [comment]
fixed it

**Comment by vprelovac** [comment]
THanks!

**Pull request merged**
