### PR TITLE
Fix broken Vertex completion; Use GA/Stable vertex APIs

### PR DESCRIPTION
**Pull request by laksh-bhat**
```python
>>> import llms
>>> model = llms.init(model='chat-bison')
Found chat-bison in GoogleProvider
>>> result = model.complete('2+2 is: ')
>>> result.text
'4'

>>> model = llms.init(model='text-bison')
Found text-bison in GoogleProvider
>>> result = model.complete('2+2 is: ')
>>> result.text
'4'


```

### CODE REVIEW

**Comment by laksh-bhat** [comment]
@vprelovac Vertex is broken at the moment as it's moved up to GA status - please review

**Comment by vprelovac** [comment]
@laksh-bhat Thanks. What do you think about switching to their https://developers.generativeai.google/api/python/google/generativeai API ?

Vertex is more like Azure and is hard to set up.

**Comment by laksh-bhat** [comment]
Agreed that vertex hard to setup but the genai client while great for dev setups, gets rate limited and not scalable for enterprise uses. If there is appetite, we can add `google-generativeai` under `google-genai` provider (and disambiguating it from `google-vertex` provider)

**Comment by vprelovac** [comment]
Yes would love that.

**Pull request merged**
